apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app-a
  name: app-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app-a
    spec:
      containers:
      - image: app-a
        name: app-a
        resources: {}
status: {}
