version: "3"

services:
  postgresql:
    container_name: postgres
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=user
      - POSTGRESQL_DATABASE=postgres
  kasandra:
    container_name: cassandra
    image: cassandra:4.0.3
    ports:
      - 9042:9042
    volumes:
      - ~/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=citizi


