apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-replica
  labels:
    app: rep-ap
spec:
 - template:
     metadata:
       name: test-name
       labels:
         app: test-label
     spec:
       containers:
         - name: nginx-container
           image: nginx

 - replicas: 2
