{{if eq .Values.name "db"}}
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: {{.Values.name}}-volume
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 1Gi 
  hostPath:
    /home/lucky/data
{{end}}
    
     
 