{{if eq .Values.name "db"}}
apiVersion: v1
kind: PersistentVolume 
metadata:
  name: {{.Values.name}}-volume
  labels:
    type: local
spec:
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce 
  capacity:
    storage: 1Gi 
  hostPath:
    path: /mnt/db
{{end}}
    
     
 