{{if eq .Values.name "db"}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: {{.Values.name}}-claim
spec:
  accessModes:
    - ReadWriteOnce 
  resources:
    requests:
      storage: 500Mi
{{end}}
       
    
     
 