server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: appa
          uri: http://localhost:8081/
          predicates:
            - Path=/appa/**
        - id: appb
          uri: http://localhost:8082/
          predicates:
            - Path=/appb/**