apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b
  labels:
    app: app-b
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-b
  strategy: {}
  template:
    metadata:
      labels:
        app: app-b
    spec:
      containers:
        - image: localhost:32000/appb:v2
          name: app-b
#          imagePullPolicy: Never
          resources: {}
          ports:
            - containerPort: 8082

status: {}

---
apiVersion: v1
kind: Service
metadata:
  name: app-b
  labels:
    app:  app-b
spec:
  selector:
    app: app-b
#  type: LoadBalancer
  ports:
    - name: aap-b
      port: 8082
      targetPort: 8082
      protocol: TCP

